/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedZonesRouteImport } from './routes/_authenticated.zones'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated.schedules'
import { Route as AuthenticatedEnergyRouteImport } from './routes/_authenticated.energy'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedApartmentsRouteImport } from './routes/_authenticated.apartments'
import { Route as AuthenticatedThermostatsIdRouteImport } from './routes/_authenticated.thermostats.$id'
import { Route as AuthenticatedApartmentsIdRouteImport } from './routes/_authenticated.apartments.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedZonesRoute = AuthenticatedZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEnergyRoute = AuthenticatedEnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApartmentsRoute = AuthenticatedApartmentsRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedThermostatsIdRoute =
  AuthenticatedThermostatsIdRouteImport.update({
    id: '/thermostats/$id',
    path: '/thermostats/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApartmentsIdRoute =
  AuthenticatedApartmentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedApartmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/apartments': typeof AuthenticatedApartmentsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/energy': typeof AuthenticatedEnergyRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/zones': typeof AuthenticatedZonesRoute
  '/apartments/$id': typeof AuthenticatedApartmentsIdRoute
  '/thermostats/$id': typeof AuthenticatedThermostatsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/apartments': typeof AuthenticatedApartmentsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/energy': typeof AuthenticatedEnergyRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/zones': typeof AuthenticatedZonesRoute
  '/apartments/$id': typeof AuthenticatedApartmentsIdRoute
  '/thermostats/$id': typeof AuthenticatedThermostatsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/apartments': typeof AuthenticatedApartmentsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/energy': typeof AuthenticatedEnergyRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/zones': typeof AuthenticatedZonesRoute
  '/_authenticated/apartments/$id': typeof AuthenticatedApartmentsIdRoute
  '/_authenticated/thermostats/$id': typeof AuthenticatedThermostatsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/apartments'
    | '/dashboard'
    | '/energy'
    | '/schedules'
    | '/settings'
    | '/zones'
    | '/apartments/$id'
    | '/thermostats/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/apartments'
    | '/dashboard'
    | '/energy'
    | '/schedules'
    | '/settings'
    | '/zones'
    | '/apartments/$id'
    | '/thermostats/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/apartments'
    | '/_authenticated/dashboard'
    | '/_authenticated/energy'
    | '/_authenticated/schedules'
    | '/_authenticated/settings'
    | '/_authenticated/zones'
    | '/_authenticated/apartments/$id'
    | '/_authenticated/thermostats/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/zones': {
      id: '/_authenticated/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof AuthenticatedZonesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/energy': {
      id: '/_authenticated/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof AuthenticatedEnergyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apartments': {
      id: '/_authenticated/apartments'
      path: '/apartments'
      fullPath: '/apartments'
      preLoaderRoute: typeof AuthenticatedApartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/thermostats/$id': {
      id: '/_authenticated/thermostats/$id'
      path: '/thermostats/$id'
      fullPath: '/thermostats/$id'
      preLoaderRoute: typeof AuthenticatedThermostatsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apartments/$id': {
      id: '/_authenticated/apartments/$id'
      path: '/$id'
      fullPath: '/apartments/$id'
      preLoaderRoute: typeof AuthenticatedApartmentsIdRouteImport
      parentRoute: typeof AuthenticatedApartmentsRoute
    }
  }
}

interface AuthenticatedApartmentsRouteChildren {
  AuthenticatedApartmentsIdRoute: typeof AuthenticatedApartmentsIdRoute
}

const AuthenticatedApartmentsRouteChildren: AuthenticatedApartmentsRouteChildren =
  {
    AuthenticatedApartmentsIdRoute: AuthenticatedApartmentsIdRoute,
  }

const AuthenticatedApartmentsRouteWithChildren =
  AuthenticatedApartmentsRoute._addFileChildren(
    AuthenticatedApartmentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedApartmentsRoute: typeof AuthenticatedApartmentsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnergyRoute: typeof AuthenticatedEnergyRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedZonesRoute: typeof AuthenticatedZonesRoute
  AuthenticatedThermostatsIdRoute: typeof AuthenticatedThermostatsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApartmentsRoute: AuthenticatedApartmentsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnergyRoute: AuthenticatedEnergyRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedZonesRoute: AuthenticatedZonesRoute,
  AuthenticatedThermostatsIdRoute: AuthenticatedThermostatsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
